// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC9NhRmWrIWpxKA_nHLL-iknYM17MXpL4',
    appId: '1:856671348212:web:0059a2087a688a4a4d45a1',
    messagingSenderId: '856671348212',
    projectId: 'clinicgo-11d9e',
    authDomain: 'clinicgo-11d9e.firebaseapp.com',
    storageBucket: 'clinicgo-11d9e.firebasestorage.app',
    measurementId: 'G-8L6ZV5DGG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy6d0gh_lO3Ws5lXASI--I458enwbtNY4',
    appId: '1:856671348212:android:93040e6c04c4a5954d45a1',
    messagingSenderId: '856671348212',
    projectId: 'clinicgo-11d9e',
    storageBucket: 'clinicgo-11d9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1m4vnPdQ7wpQT_ziQob25L-UX56vNdH8',
    appId: '1:856671348212:ios:d7a87d8401746b174d45a1',
    messagingSenderId: '856671348212',
    projectId: 'clinicgo-11d9e',
    storageBucket: 'clinicgo-11d9e.firebasestorage.app',
    iosBundleId: 'com.example.fourUApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1m4vnPdQ7wpQT_ziQob25L-UX56vNdH8',
    appId: '1:856671348212:ios:7e2474d08b5f21b24d45a1',
    messagingSenderId: '856671348212',
    projectId: 'clinicgo-11d9e',
    storageBucket: 'clinicgo-11d9e.firebasestorage.app',
    iosBundleId: 'com.example.clinicGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC9NhRmWrIWpxKA_nHLL-iknYM17MXpL4',
    appId: '1:856671348212:web:78342a2b401fcfa24d45a1',
    messagingSenderId: '856671348212',
    projectId: 'clinicgo-11d9e',
    authDomain: 'clinicgo-11d9e.firebaseapp.com',
    storageBucket: 'clinicgo-11d9e.firebasestorage.app',
    measurementId: 'G-HPJMKM3TXC',
  );
}
